### ISSUE TITLE
Multiple triggers?

### ISSUE THREAD

**Issue by stacecom** [jarshwah/slack-regex-responder#2]
I've had great success having it respond to a single regex.  What I'd like is to add a second regex for a different response.  I thought this would work, but is not - only the first regex triggers and the second never does:

```
token: 'foo'
rules:
  FIRST:
    pattern: '\b((AREQ|TKT|INC|TASK|RITM)\d{7})\b'
    response: 'foo=\1'
    rooms:
      - 'systems'
  SECOND:
    pattern: '\b(F\d{1}-\d{6})\b'
    response: 'bar=\1'
    rooms:
      - 'systems'
```
